name = "SystemLevelHamiltonian"
uuid = "a0b4ee4f-8fee-4001-b7c2-b2f55611dd49"
authors = ["Jeffrey Wack <jeffwack111@gmail.com> and contributors"]
version = "0.7.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SecondQuantizedAlgebra = "f7aa4685-e143-4cb6-a7f3-073579757907"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
LinearAlgebra = "1.11.0"
SecondQuantizedAlgebra = "0.3.1"
Symbolics = "6.38.0"
julia = "1.11.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
